class Autogenerated {
  List<Floors> floors;

  Autogenerated({this.floors});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['floors'] != null) {
      floors = new List<Floors>();
      json['floors'].forEach((v) {
        floors.add(new Floors.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.floors != null) {
      data['floors'] = this.floors.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Floors {
  int id;
  String floorName;
  int floorNo;
  String createdAt;
  String updatedAt;

  Floors(
      {this.id, this.floorName, this.floorNo, this.createdAt, this.updatedAt});

  Floors.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    floorName = json['floor_name'];
    floorNo = json['floor_no'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['floor_name'] = this.floorName;
    data['floor_no'] = this.floorNo;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
