import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:project_trip_app/homeDetail/detail.dart';
import 'package:project_trip_app/homeDetail/details.dart';
//import 'package:project_trip_app/model/floor_room.dart';
import 'package:project_trip_app/model/room_types.dart';

class GridTwo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return GridTwoState();
  }
} //Stateful

class GridTwoState extends State<GridTwo> {
  var url = "http://hotel-booking.minpike.me/api/setup/room_type";


  Autogenerated autoGenerated;

  @override
  void initState() {
    fetchData();
  }

  fetchData() async {
    var res = await http.get(url);

    var decodeJson = jsonDecode(res.body);

    autoGenerated = Autogenerated.fromJson(decodeJson);

    print(autoGenerated.toJson());
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(

      body: Container(
        decoration: BoxDecoration(
            image: DecorationImage(
                image: AssetImage("images/one.jpg"), fit: BoxFit.cover)),
        child: autoGenerated == null
            ? Center(
                child: CircularProgressIndicator(),
              )
            : GridView.count(
                crossAxisCount: 2,
                children: autoGenerated.roomTypes
                    .map((room) => Card(
                      elevation: 10.0,
                      margin: EdgeInsets.all(7.0),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Container(
                        child: InkWell(
                          child: Card(
                            elevation: 10.0,
                            child: Hero(
                              tag: room.image,
                              child: Column(
                                crossAxisAlignment:
                                    CrossAxisAlignment.center,
                                children: <Widget>[
                                  Image.network(
                                    room.image,
                                    height: 150.0,
                                    width: 200.0,
                                    fit: BoxFit.cover,
                                  ),
                                  SizedBox(
                                    height: 5.0,
                                  ),
                                  Padding(
                                    padding: const EdgeInsets.all(1.0),
                                    child: Text(
                                      room.roomName,
                                      style: TextStyle(
                                        fontSize: 12,
                                        color: Colors.deepOrange,
                                      ),
                                    ),
                                  )
                                ],
                              ),
                            ),
                          ),
                          onTap: () {
                            Navigator.push(context, MaterialPageRoute(
                              builder: (context) =>
                                  HotelDetails(room)
                            ));

                          },
                        ),
                      ),
                    ))
                    .toList()),
      ),
    );
  }
} //State
